redmine:
  url: <%= ENV['REDMINE_URL'] %>
  api_key: <%= ENV['REDMINE_API_KEY'] %>
  basic_auth:
    username: <%= ENV['REDMINE_BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['REDMINE_BASIC_AUTH_PASSWORD'] %>

